### ISSUE TITLE
bug in line 4

### ISSUE THREAD

**Issue by Mati2906** [visus100/pierwsze_repo#4]
ther is a logic error

**Comment by Mati2906** [comment]
przed testem
```
test

```
za testem

**Comment by visus100** [comment]
ok zamykam

**Comment by visus100** [comment]
ok poprawione

**Comment by Mati2906** [comment]
done

**Comment by Mati2906** [comment]
wrong

**Comment by Mati2906** [comment]
##### test

- [ ] 
****test

- [x] _test_

```
#[
reviev test

test2

teste3

test4](url
Duplicate of #)
```

**Comment by Mati2906** [comment]
https://github.com/visus100/pierwsze_repo/blob/master/Chuj.txt#l1

**Comment by Mati2906** [comment]
https://github.com/visus100/pierwsze_repo/commit/c4b1f2c662957201d72102513db6c7ef04dbc0ca

**Comment by Mati2906** [comment]
https://github.com/visus100/pierwsze_repo/commit/c4b1f2c662957201d72102513db6c7ef04dbc0ca

test_reviewer.txt #1

**Comment by visus100** [comment]
https://github.com/visus100/pierwsze_repo/blob/d3817a4bbb0da0cc03fcda314a10cee6fd970780/test_doc_1.txt#L1-L14

ty vulgarisie
